// App.js
import React, {useState} from 'react';
import {View, Text, StyleSheet, TextInput, Switch} from 'react-native';
import ModalSelector from 'react-native-modal-selector';
import {useSelector} from 'react-redux';
import {selectCountriesData} from '../../redux/reducers/registration/registration.selectors';
import Input from './Input';

const Dropdown = ({placeholder, value, setValue}) => {
  const [countryName, setCountryName] = useState('');
  const countries = useSelector(state => state);
  const data = countries?.registration?.countiesData?.data;
  // const data = [
  //   {alpha2Code: 'AU', id: 1022, name: 'ავსტრალია'},
  //   {alpha2Code: 'AT', id: 1023, name: 'ავსტრია'},
  //   {alpha2Code: 'AF', id: 1009, name: 'ავღანეთი'},
  //   {alpha2Code: 'AZ', id: 1024, name: 'აზერბაიჯანი'},
  //   {alpha2Code: 'AX', id: 1010, name: 'ალანდის კუნძულები'},
  //   {alpha2Code: 'AL', id: 1011, name: 'ალბანეთი'},
  //   {alpha2Code: 'DZ', id: 1012, name: 'ალჟირი'},
  //   {alpha2Code: 'AS', id: 1013, name: 'ამერიკის სამოა'},
  //   {alpha2Code: 'AI', id: 1016, name: 'ანგილია'},
  //   {alpha2Code: 'AO', id: 1015, name: 'ანგოლა'},
  //   {alpha2Code: 'AD', id: 1014, name: 'ანდორა'},
  //   {alpha2Code: 'AQ', id: 1017, name: 'ანტარქტიდა'},
  //   {alpha2Code: 'AG', id: 1018, name: 'ანტიგუა და ბარბუდა'},
  //   {alpha2Code: 'AE', id: 1241, name: 'არაბთა გაერთიანებული საამიროები'},
  //   {alpha2Code: 'AR', id: 1019, name: 'არგენტინა'},
  //   {alpha2Code: 'AW', id: 1021, name: 'არუბა'},
  //   {alpha2Code: 'TL', id: 1229, name: 'აღმოსავლეთი ტიმორი'},
  //   {alpha2Code: 'US', id: 1243, name: 'აშშ'},
  //   {alpha2Code: 'UM', id: 1244, name: 'აშშ-ის მიმდებარე მცირე კუნძულები'},
  //   {alpha2Code: 'NZ', id: 1166, name: 'ახალი ზელანდია'},
  //   {alpha2Code: 'NC', id: 1165, name: 'ახალი კალედონია'},
  //   {alpha2Code: 'BD', id: 1027, name: 'ბანგლადეში'},
  //   {alpha2Code: 'BB', id: 1028, name: 'ბარბადოსი'},
  //   {alpha2Code: 'BS', id: 1025, name: 'ბაჰამის კუნძულები'},
  //   {alpha2Code: 'BH', id: 1026, name: 'ბაჰრეინი'},
  //   {alpha2Code: 'BY', id: 1029, name: 'ბელარუსი'},
  //   {alpha2Code: 'BE', id: 1030, name: 'ბელგია'},
  //   {alpha2Code: 'BZ', id: 1031, name: 'ბელიზი'},
  //   {alpha2Code: 'BJ', id: 1032, name: 'ბენინი'},
  //   {alpha2Code: 'BM', id: 1033, name: 'ბერმუდის კუნძულები'},
  //   {alpha2Code: 'BO', id: 1035, name: 'ბოლივია'},
  //   {alpha2Code: 'BA', id: 1037, name: 'ბოსნია და ჰერცეგოვინა'},
  //   {alpha2Code: 'BW', id: 1038, name: 'ბოტსვანა'},
  //   {alpha2Code: 'BR', id: 1040, name: 'ბრაზილია'},
  //   {alpha2Code: 'IO', id: 1041, name: 'ბრიტანეთის ინდოეთის ოკეანის ტერიტორია'},
  //   {alpha2Code: 'BN', id: 1042, name: 'ბრუნეი დარუსალამი'},
  //   {alpha2Code: 'BV', id: 1039, name: 'ბუვე'},
  //   {alpha2Code: 'BG', id: 1043, name: 'ბულგარეთი'},
  //   {alpha2Code: 'BF', id: 1044, name: 'ბურკინა-ფასო'},
  //   {alpha2Code: 'BI', id: 1045, name: 'ბურუნდი'},
  //   {alpha2Code: 'BT', id: 1034, name: 'ბჰუტანი'},
  //   {alpha2Code: 'GA', id: 1089, name: 'გაბონი'},
  //   {alpha2Code: 'GB', id: 1242, name: 'გაერთიანებული სამეფო'},
  //   {alpha2Code: 'GY', id: 1103, name: 'გაიანა'},
  //   {alpha2Code: 'GM', id: 1090, name: 'გამბია'},
  //   {alpha2Code: 'GH', id: 1092, name: 'განა'},
  //   {alpha2Code: 'DE', id: 1091, name: 'გერმანია'},
  //   {alpha2Code: 'GG', id: 1100, name: 'გერნზი'},
  //   {alpha2Code: 'GP', id: 1097, name: 'გვადელუპა'},
  //   {alpha2Code: 'GT', id: 1099, name: 'გვატემალა'},
  //   {alpha2Code: 'GN', id: 1101, name: 'გვინეა'},
  //   {alpha2Code: 'GW', id: 1102, name: 'გვინეა-ბისაუ'},
  //   {alpha2Code: 'GI', id: 1093, name: 'გიბრალტარი'},
  //   {alpha2Code: 'GD', id: 1096, name: 'გრენადა'},
  //   {alpha2Code: 'GL', id: 1095, name: 'გრენლანდია'},
  //   {alpha2Code: 'GU', id: 1098, name: 'გუამი'},
  //   {alpha2Code: 'DK', id: 1069, name: 'დანია'},
  //   {alpha2Code: 'EH', id: 1253, name: 'დასავლეთი საჰარა'},
  //   {alpha2Code: 'DM', id: 1071, name: 'დომინიკა'},
  //   {alpha2Code: 'DO', id: 1072, name: 'დომინიკელთა რესპუბლიკა'},
  //   {alpha2Code: 'EG', id: 1074, name: 'ეგვიპტე'},
  //   {alpha2Code: 'ET', id: 1080, name: 'ეთიოპია'},
  //   {alpha2Code: 'EC', id: 1073, name: 'ეკვადორი'},
  //   {alpha2Code: 'GQ', id: 1076, name: 'ეკვატორული გვინეა'},
  //   {alpha2Code: 'IQ', id: 1114, name: 'ერაყი'},
  //   {alpha2Code: 'ER', id: 1077, name: 'ერიტრეა'},
  //   {alpha2Code: 'SZ', id: 1079, name: 'ესვატინი'},
  //   {alpha2Code: 'ES', id: 1217, name: 'ესპანეთი'},
  //   {alpha2Code: 'EE', id: 1078, name: 'ესტონეთი'},
  //   {alpha2Code: 'VU', id: 1247, name: 'ვანუატუ'},
  //   {alpha2Code: 'VA', id: 1106, name: 'ვატიკანი (წმინდა საყდარი)'},
  //   {alpha2Code: 'VE', id: 1248, name: 'ვენესუელა'},
  //   {alpha2Code: 'VN', id: 1249, name: 'ვიეტნამი'},
  //   {alpha2Code: 'VI', id: 1251, name: 'ვირჯინის კუნძულები (აშშ-ის)'},
  //   {alpha2Code: 'VG', id: 1250, name: 'ვირჯინის კუნძულები (ბრიტანეთის)'},
  //   {alpha2Code: 'ZM', id: 1255, name: 'ზამბია'},
  //   {alpha2Code: 'ZW', id: 1256, name: 'ზიმბაბვე'},
  //   {alpha2Code: 'TR', id: 1235, name: 'თურქეთი'},
  //   {alpha2Code: 'TM', id: 1236, name: 'თურქმენეთი'},
  //   {alpha2Code: 'JM', id: 1119, name: 'იამაიკა'},
  //   {alpha2Code: 'JP', id: 1120, name: 'იაპონია'},
  //   {alpha2Code: 'YE', id: 1254, name: 'იემენი'},
  //   {alpha2Code: 'IN', id: 1111, name: 'ინდოეთი'},
  //   {alpha2Code: 'ID', id: 1112, name: 'ინდონეზია'},
  //   {alpha2Code: 'JO', id: 1122, name: 'იორდანია'},
  //   {alpha2Code: 'IR', id: 1113, name: 'ირანის მუსულმანური რესპუბლიკა'},
  //   {alpha2Code: 'IE', id: 1115, name: 'ირლანდია'},
  //   {alpha2Code: 'IS', id: 1110, name: 'ისლანდია'},
  //   {alpha2Code: 'IL', id: 1117, name: 'ისრაელი'},
  //   {alpha2Code: 'IT', id: 1118, name: 'იტალია'},
  //   {alpha2Code: 'CV', id: 1046, name: 'კაბო-ვერდე'},
  //   {alpha2Code: 'KY', id: 1050, name: 'კაიმანის კუნძულები'},
  //   {alpha2Code: 'KH', id: 1047, name: 'კამბოჯა'},
  //   {alpha2Code: 'CM', id: 1048, name: 'კამერუნი'},
  //   {alpha2Code: 'CA', id: 1049, name: 'კანადა'},
  //   {alpha2Code: 'BQ', id: 1036, name: 'კარიბის ნიდერლანდები'},
  //   {alpha2Code: 'QA', id: 1188, name: 'კატარი'},
  //   {alpha2Code: 'KE', id: 1124, name: 'კენია'},
  //   {alpha2Code: 'CY', id: 1067, name: 'კვიპროსი'},
  //   {alpha2Code: 'KI', id: 1125, name: 'კირიბატი'},
  //   {alpha2Code: 'CW', id: 1066, name: 'კიურასაო'},
  //   {alpha2Code: 'CO', id: 1057, name: 'კოლუმბია'},
  //   {alpha2Code: 'KM', id: 1058, name: 'კომორის კუნძულების კავშირი'},
  //   {alpha2Code: 'CG', id: 1059, name: 'კონგო'},
  //   {alpha2Code: 'CD', id: 1060, name: 'კონგოს დემოკრატიული რესპუბლიკა'},
  //   {alpha2Code: 'CR', id: 1062, name: 'კოსტა-რიკა'},
  //   {alpha2Code: 'CI', id: 1063, name: 'კოტ-დ’ივუარი'},
  //   {alpha2Code: 'CU', id: 1065, name: 'კუბა'},
  //   {alpha2Code: 'CK', id: 1061, name: 'კუკის კუნძულები'},
  //   {alpha2Code: 'IM', id: 1116, name: 'კუნძული მენი'},
  //   {
  //     alpha2Code: 'LA',
  //     id: 1130,
  //     name: 'ლაოსის სახალხო დემოკრატიული რესპუბლიკა',
  //   },
  //   {alpha2Code: 'LV', id: 1131, name: 'ლატვია'},
  //   {alpha2Code: 'LS', id: 1133, name: 'ლესოთო'},
  //   {alpha2Code: 'LB', id: 1132, name: 'ლიბანი'},
  //   {alpha2Code: 'LR', id: 1134, name: 'ლიბერია'},
  //   {alpha2Code: 'LY', id: 1135, name: 'ლიბიის არაბული ჯამაჰირია'},
  //   {alpha2Code: 'LT', id: 1137, name: 'ლიეტუვა'},
  //   {alpha2Code: 'LI', id: 1136, name: 'ლიხტენშტაინი'},
  //   {alpha2Code: 'LU', id: 1138, name: 'ლუქსემბურგი'},
  //   {alpha2Code: 'MG', id: 1140, name: 'მადაგასკარი'},
  //   {alpha2Code: 'MU', id: 1149, name: 'მავრიკი'},
  //   {alpha2Code: 'MR', id: 1148, name: 'მავრიტანია'},
  //   {alpha2Code: 'YT', id: 1150, name: 'მაიოტა'},
  //   {alpha2Code: 'MO', id: 1139, name: 'მაკაო'},
  //   {alpha2Code: 'MW', id: 1141, name: 'მალავი'},
  //   {alpha2Code: 'MY', id: 1142, name: 'მალაიზია'},
  //   {alpha2Code: 'MV', id: 1143, name: 'მალდივი'},
  //   {alpha2Code: 'ML', id: 1144, name: 'მალი'},
  //   {alpha2Code: 'MT', id: 1145, name: 'მალტა'},
  //   {alpha2Code: 'MA', id: 1158, name: 'მაროკო'},
  //   {alpha2Code: 'MQ', id: 1147, name: 'მარტინიკა'},
  //   {alpha2Code: 'MH', id: 1146, name: 'მარშალის კუნძულები'},
  //   {alpha2Code: 'MX', id: 1151, name: 'მექსიკა'},
  //   {alpha2Code: 'MM', id: 1160, name: 'მიანმარი'},
  //   {alpha2Code: 'FM', id: 1152, name: 'მიკრონეზიის ფედერაციული შტატები'},
  //   {alpha2Code: 'MZ', id: 1159, name: 'მოზამბიკი'},
  //   {alpha2Code: 'MD', id: 1153, name: 'მოლდოვას რესპუბლიკა'},
  //   {alpha2Code: 'MC', id: 1154, name: 'მონაკო'},
  //   {alpha2Code: 'MS', id: 1157, name: 'მონსერატი'},
  //   {alpha2Code: 'ME', id: 1156, name: 'მონტენეგრო'},
  //   {alpha2Code: 'MN', id: 1155, name: 'მონღოლეთი'},
  //   {alpha2Code: 'NA', id: 1161, name: 'ნამიბია'},
  //   {alpha2Code: 'NR', id: 1162, name: 'ნაურუ'},
  //   {alpha2Code: 'NP', id: 1163, name: 'ნეპალი'},
  //   {alpha2Code: 'NE', id: 1168, name: 'ნიგერი'},
  //   {alpha2Code: 'NG', id: 1169, name: 'ნიგერია'},
  //   {alpha2Code: 'NL', id: 1164, name: 'ნიდერლანდები'},
  //   {alpha2Code: 'NI', id: 1167, name: 'ნიკარაგუა'},
  //   {alpha2Code: 'NU', id: 1170, name: 'ნიუე'},
  //   {alpha2Code: 'NO', id: 1174, name: 'ნორვეგია'},
  //   {alpha2Code: 'NF', id: 1171, name: 'ნორფოლკი'},
  //   {alpha2Code: 'OM', id: 1175, name: 'ომანი'},
  //   {alpha2Code: 'PK', id: 1176, name: 'პაკისტანი'},
  //   {alpha2Code: 'PW', id: 1177, name: 'პალაუ'},
  //   {alpha2Code: 'PS', id: 1178, name: 'პალესტინის ტერიტორიები, ოკუპირებული'},
  //   {alpha2Code: 'PA', id: 1179, name: 'პანამა'},
  //   {alpha2Code: 'PG', id: 1180, name: 'პაპუა-ახალი გვინეა'},
  //   {alpha2Code: 'PY', id: 1181, name: 'პარაგვაი'},
  //   {alpha2Code: 'PE', id: 1182, name: 'პერუ'},
  //   {alpha2Code: 'PN', id: 1184, name: 'პიტკერნის კუნძულები'},
  //   {alpha2Code: 'PL', id: 1185, name: 'პოლონეთი'},
  //   {alpha2Code: 'PT', id: 1186, name: 'პორტუგალია'},
  //   {alpha2Code: 'PR', id: 1187, name: 'პუერტო-რიკო'},
  //   {alpha2Code: 'RE', id: 1189, name: 'რეიუნიონი'},
  //   {alpha2Code: 'RW', id: 1192, name: 'რუანდა'},
  //   {alpha2Code: 'RO', id: 1190, name: 'რუმინეთი'},
  //   {alpha2Code: 'RU', id: 1191, name: 'რუსეთი'},
  //   {alpha2Code: 'GR', id: 1094, name: 'საბერძნეთი'},
  //   {alpha2Code: 'SV', id: 1075, name: 'სალვადორი'},
  //   {alpha2Code: 'WS', id: 1200, name: 'სამოა'},
  //   {alpha2Code: 'ZA', id: 1214, name: 'სამხრეთ აფრიკის რესპუბლიკა'},
  //   {
  //     alpha2Code: 'GS',
  //     id: 1215,
  //     name: 'სამხრეთი გეორგია და სამხრეთ სენდვიჩის კუნძულები',
  //   },
  //   {alpha2Code: 'KR', id: 1127, name: 'სამხრეთი კორეა'},
  //   {alpha2Code: 'SS', id: 1216, name: 'სამხრეთი სუდანი'},
  //   {alpha2Code: 'SM', id: 1201, name: 'სან-მარინო'},
  //   {alpha2Code: 'ST', id: 1202, name: 'სან-ტომე და პრინსიპი'},
  //   {alpha2Code: 'SA', id: 1203, name: 'საუდის არაბეთი'},
  //   {alpha2Code: 'FR', id: 1085, name: 'საფრანგეთი'},
  //   {alpha2Code: 'GF', id: 1086, name: 'საფრანგეთის გვიანა'},
  //   {alpha2Code: 'PF', id: 1087, name: 'საფრანგეთის პოლინეზია'},
  //   {
  //     alpha2Code: 'TF',
  //     id: 1088,
  //     name: 'საფრანგეთის სამხრეთული და ანტარქტიდული ტერიტორია',
  //   },
  //   {alpha2Code: 'GE', id: 1, name: 'საქართველო'},
  //   {alpha2Code: 'SC', id: 1206, name: 'სეიშელი'},
  //   {alpha2Code: 'BL', id: 1193, name: 'სენ-ბართელმი'},
  //   {alpha2Code: 'SN', id: 1204, name: 'სენეგალი'},
  //   {alpha2Code: 'PM', id: 1198, name: 'სენ-პიერი და მიკელონი'},
  //   {alpha2Code: 'VC', id: 1199, name: 'სენტ-ვინსენტი და გრენადინები'},
  //   {alpha2Code: 'KN', id: 1195, name: 'სენტ-კიტსი და ნევისი'},
  //   {alpha2Code: 'LC', id: 1196, name: 'სენტ-ლუსია'},
  //   {alpha2Code: 'RS', id: 1205, name: 'სერბეთი'},
  //   {alpha2Code: 'SJ', id: 1221, name: 'სვალბარდი და იან-მაიენი'},
  //   {alpha2Code: 'SL', id: 1207, name: 'სიერა-ლეონე'},
  //   {alpha2Code: 'SG', id: 1208, name: 'სინგაპური'},
  //   {alpha2Code: 'SX', id: 1209, name: 'სინტ-მარტენი'},
  //   {alpha2Code: 'SY', id: 1224, name: 'სირიის არაბთა რესპუბლიკა'},
  //   {alpha2Code: 'SK', id: 1210, name: 'სლოვაკეთი'},
  //   {alpha2Code: 'SI', id: 1211, name: 'სლოვენია'},
  //   {alpha2Code: 'SB', id: 1212, name: 'სოლომონის კუნძულები'},
  //   {alpha2Code: 'SO', id: 1213, name: 'სომალი'},
  //   {alpha2Code: 'AM', id: 1020, name: 'სომხეთი'},
  //   {alpha2Code: 'SD', id: 1219, name: 'სუდანი'},
  //   {alpha2Code: 'SR', id: 1220, name: 'სურინამი'},
  //   {alpha2Code: 'TW', id: 1225, name: 'ტაივანი'},
  //   {alpha2Code: 'TH', id: 1228, name: 'ტაილანდი'},
  //   {alpha2Code: 'TZ', id: 1227, name: 'ტანზანიის გაერთიანებული რესპუბლიკა'},
  //   {alpha2Code: 'TJ', id: 1226, name: 'ტაჯიკეთი'},
  //   {alpha2Code: 'TC', id: 1237, name: 'ტერქსისა და კაიკოსის კუნძულები'},
  //   {alpha2Code: 'TG', id: 1230, name: 'ტოგო'},
  //   {alpha2Code: 'TK', id: 1231, name: 'ტოკელაუ'},
  //   {alpha2Code: 'TO', id: 1232, name: 'ტონგა'},
  //   {alpha2Code: 'TT', id: 1233, name: 'ტრინიდადი და ტობაგო'},
  //   {alpha2Code: 'TV', id: 1238, name: 'ტუვალუ'},
  //   {alpha2Code: 'TN', id: 1234, name: 'ტუნისი'},
  //   {alpha2Code: 'UG', id: 1239, name: 'უგანდა'},
  //   {alpha2Code: 'UZ', id: 1246, name: 'უზბეკეთი'},
  //   {alpha2Code: 'UA', id: 1240, name: 'უკრაინა'},
  //   {alpha2Code: 'HU', id: 1109, name: 'უნგრეთი'},
  //   {alpha2Code: 'WF', id: 1252, name: 'უოლისი და ფუტუნა'},
  //   {alpha2Code: 'UY', id: 1245, name: 'ურუგვაი'},
  //   {alpha2Code: 'FO', id: 1082, name: 'ფარერის კუნძულები'},
  //   {alpha2Code: 'PH', id: 1183, name: 'ფილიპინები'},
  //   {alpha2Code: 'FI', id: 1084, name: 'ფინეთი'},
  //   {alpha2Code: 'FJ', id: 1083, name: 'ფიჯი'},
  //   {alpha2Code: 'FK', id: 1081, name: 'ფოლკლენდის კუნძულები (მალვინები)'},
  //   {alpha2Code: 'CC', id: 1056, name: 'ქოქოსის კუნძულები'},
  //   {alpha2Code: 'KW', id: 1128, name: 'ქუვეითი'},
  //   {alpha2Code: 'KZ', id: 1123, name: 'ყაზახეთი'},
  //   {alpha2Code: 'KG', id: 1129, name: 'ყირგიზეთი'},
  //   {alpha2Code: 'SE', id: 1222, name: 'შვედეთი'},
  //   {alpha2Code: 'CH', id: 1223, name: 'შვეიცარია'},
  //   {alpha2Code: 'CX', id: 1055, name: 'შობის კუნძული'},
  //   {alpha2Code: 'LK', id: 1218, name: 'შრი-ლანკა'},
  //   {alpha2Code: 'TD', id: 1052, name: 'ჩადი'},
  //   {alpha2Code: 'CZ', id: 1068, name: 'ჩეხეთი'},
  //   {alpha2Code: 'CL', id: 1053, name: 'ჩილე'},
  //   {alpha2Code: 'CN', id: 1054, name: 'ჩინეთი'},
  //   {alpha2Code: 'MP', id: 1173, name: 'ჩრდილოეთ მარიანას კუნძულები'},
  //   {alpha2Code: 'KP', id: 1126, name: 'ჩრდილოეთი კორეა'},
  //   {alpha2Code: 'MK', id: 1172, name: 'ჩრდილოეთი მაკედონია'},
  //   {alpha2Code: 'CF', id: 1051, name: 'ცენტრალური აფრიკის რესპუბლიკა'},
  //   {alpha2Code: 'SH', id: 1194, name: 'წმინდა ელენეს კუნძული'},
  //   {alpha2Code: 'MF', id: 1197, name: 'წმინდა მარტინი (საფრანგეთის ნაწილი)'},
  //   {alpha2Code: 'HR', id: 1064, name: 'ხორვატია'},
  //   {alpha2Code: 'JE', id: 1121, name: 'ჯერზი'},
  //   {alpha2Code: 'DJ', id: 1070, name: 'ჯიბუტი'},
  //   {alpha2Code: 'HT', id: 1104, name: 'ჰაიტი'},
  //   {alpha2Code: 'HM', id: 1105, name: 'ჰერდი და მაკდონალდის კუნძულები'},
  //   {alpha2Code: 'HK', id: 1108, name: 'ჰონგ-კონგი'},
  //   {alpha2Code: 'HN', id: 1107, name: 'ჰონდურასი'},
  // ];

  const handleOptionChange = option => {
    setValue(option.id);
    setCountryName(option.name);
    return;
  };

  return (
    <ModalSelector
      data={data}
      onChange={handleOptionChange}
      keyExtractor={item => item.id}
      labelExtractor={item => item.name}>
      <Input
        placeholder={!countryName ? placeholder : countryName}
        value={value}
        editable={false}
      />
    </ModalSelector>
  );
};

export default Dropdown;

const styles = StyleSheet.create({});
